### ISSUE TITLE
Not sure if its working correctly...

### ISSUE THREAD

**Issue by rhamblen** [rednblkx/HomeKey-ESP32#115]
<img width="313" alt="image" src="https://github.com/user-attachments/assets/20cf9ffc-9d4d-4ee4-8862-f4d4289573ec">

firstly I dont see a reader ID and reader GUD.  is that normal???

second, 
<img width="608" alt="image" src="https://github.com/user-attachments/assets/30ba28df-4ffe-4b3b-b26b-315492a00258">
when I put a generic tag to the reader, I get an error and no tag ID.  To be honest that doesnt surprise me!

Ill do a separate message about the other issue I have that I cant see anywhere else.

**Comment by rednblkx** [comment]
Lack of ID is not normal at least, those would be assigned during pairing but that would be due to issue #116 that you opened

The nfc error can be ignored, it's just because i'm sending a homekey command to it and the card responds with an error as indicated by the last message.
The tag id is only published to the mqtt topic "hk auth", it's only printed on console when it is set to debug level.

**Comment by rhamblen** [comment]
<img width="359" alt="image" src="https://github.com/user-attachments/assets/13bcab53-7c57-475a-894b-0597ec1e5cf9">

that makes sense and fixing the pairing did then get it working correctly.
