### ISSUE TITLE
Change MQTT_STATE_TOPIC

### ISSUE THREAD

**Issue by jjuuzzii** [rednblkx/HomeKey-ESP32#38]
Hallo, 
How can i change subsribed MQTT_STATE_TOPIC to 0 and 2 ? Instead of 0 and 1

**Comment by jjuuzzii** [comment]
![IMG_5671](https://github.com/rednblkx/HomeKey-ESP32/assets/65566312/effad518-5573-45db-9a19-4249683c19b9)
S
![IMG_5670](https://github.com/rednblkx/HomeKey-ESP32/assets/65566312/1640da2d-945d-4dde-930b-ccaca610bd14)
i need to be able to change states to the id in the Foto. 
so i can control my Nuki directly with mqtt

**Comment by rednblkx** [comment]
Hi there!

Just made a change to allow state change to JAMMED(2) and UNKNOWN(3) as per spec, thank you for reminding me about it. I added this condition so it doesn't take random values and possibly crashing the thing since homekit only accepts 4 possible values for a lock.

Note that you need use the `MQTT_SET_CURRENT_STATE_TOPIC` topic to set the state to 2 or 3 as JAMMED and UNKNOWN are not target states.

**Comment by jjuuzzii** [comment]
This is the pdf https://developer.nuki.io/uploads/short-url/fcR2ntjSFMz3oHUMrIjYSU3g0O4.pdf#page6

**Comment by rednblkx** [comment]
Seems like we replied at the same time, looking at the screenshots you attached that seems to be something specific to the Nuki and not related to the HomeKit and therefore out of scope for this project.

**Comment by jjuuzzii** [comment]
https://developer.nuki.io/uploads/short-url/fcR2ntjSFMz3oHUMrIjYSU3g0O4.pdf#page6

Yes i know. I wnat to change the pubilshed id myself. 
but dont know how

**Comment by rednblkx** [comment]
with the current implementation that cannot be changed since `MQTT_STATE_TOPIC` reports the internal state of the homekit entity.
However, i like the idea, i'll try to see how i could fit this in and sure we can talk more on discord, @rednblkx

**Comment by rednblkx** [comment]
Please check out the `dev` branch, i have made some modifications and added three more options to the `config.h` file related to the subject of this issue as follows:
- `MQTT_CUSTOM_STATE_ENABLED` - Flag to enable the use of a custom states
- `MQTT_CUSTOM_STATE_TOPIC` - MQTT Topic where the custom states will be published
- `MQTT_CUSTOM_STATE_CTRL_TOPIC` - MQTT Control Topic that will translate the custom state to HomeKit state

In order to assign the custom states, when you open the `config.h` file you should see the following at the top of the file:

```cpp
// Custom Lock States to be used in MQTT_CUSTOM_STATE_CTRL_TOPIC
enum customLockStates
{
  LOCKED = 1,
  UNLOCKING = 2,
  UNLOCKED = 3,
  LOCKING = 4,
  JAMMED = 254,
  UNKNOWN = 255
};
// Custom Lock Actions to be used in MQTT_CUSTOM_STATE_TOPIC
enum customLockActions
{
  UNLOCK = 1,
  LOCK = 2
};
```

Since you provided me with the documentation for the MQTT API of your Nuki lock, the default values should match the expected ones for your lock.

In addition to all of the above, i have also added `MQTT_HOMEKEY_ALWAYS_UNLOCK` and `MQTT_HOMEKEY_ALWAYS_LOCK` which indicate if a successful homekey authentication should always set and publish the state for UNLOCK or LOCK, and is available for both `MQTT_STATE_TOPIC` and `MQTT_CUSTOM_STATE_TOPIC`. 

Let me know how it goes and you have any questions.

_**For anyone else reading this**_, if neither `MQTT_HOMEKEY_ALWAYS_UNLOCK` nor `MQTT_HOMEKEY_ALWAYS_LOCK` is enabled, a successful homekey authentication will not publish anything to `MQTT_STATE_TOPIC` and it will only publish the homekey data to `MQTT_AUTH_TOPIC` as usual. I have made this modification as it will solve any issues regarding incorrect state sent and also it does not make sense to send some arbitrary number when we are already publishing homekey data.
However, it is assumed that if you enabled `MQTT_CUSTOM_STATE_ENABLED`, you probably have a specific setup like a lock with an mqtt api like it is in this case and therefore the state will presumably be in sync so a successful homekey authentication will actually published the toggled state, e.g if current state is locked it sends the unlock command.

**Comment by rednblkx** [comment]
fixed in dev
