### ISSUE TITLE
Convert to esp-homekit-sdk

### ISSUE THREAD

**Issue by robin-hust** [rednblkx/HomeKey-ESP32#41]
Hello, first of all thank you for doing a really great project. I want to ask if there is any way to use it in esp-homekit-sdk, because my project needs to use esp-idf to deeply access some hardware functions.

**Comment by rednblkx** [comment]
short answer is no.
Long answer is you can try to use the library https://github.com/rednblkx/HK-HomeKit-Lib but you have to add the NFC Stack yourself and no idea if it works with esp-homekit-sdk as it's not currently meant for public use, see the lack of any  documentation.
Also know that this project just uses arduino as a component of esp-idf since you can't develop on the esp32 without IDF so you could also try to use this to suit your needs if you don't explicitely need esp-homekit-sdk.
